fixtures:
  repositories:
    epel: 'https://github.com/stahnma/puppet-module-epel.git'
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    vcsrepo: 'https://github.com/puppetlabs/puppetlabs-vcsrepo.git'
  symlinks:
    letsencrypt: "#{source_dir}"
